name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: src/PromoCodeFactory.WebHost

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: dotnet build ${{ env.PROJECT_NAME }}.csproj -c Release -o content

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: content
